Fix URL links
brettcannon/gidgethub pull request #135
Opened 2020-11-10 14:51 UTC by marcelotrevisani

2020-11-10 17:40 UTC, Mariatta approved these changes
Thank you. I checked the links and confirmed that the new urls are more up to date.

2020-11-10 17:42 UTC, Mariatta commented
Ah but the CI failed somehow. Please check the errors and ensure builds are passing.

2020-11-10 18:10 UTC, Mariatta requested changes
You need to update the url in line 35 too.

https://github.com/brettcannon/gidgethub/pull/135/files#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR35

2020-11-12 10:52 UTC, marcelotrevisani commented
> You need to update the url in line 35 too.
> 
> https://github.com/brettcannon/gidgethub/pull/135/files#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR35

Sorry for my delay! I already fixed that as well :)

2020-11-12 20:20 UTC, brettcannon requested changes

2020-11-12 20:20 UTC, brettcannon commented on README.rst
> +`GitHub API <https://docs.github.com/en>`_ which performs no I/O of its own (a
```suggestion
`GitHub API <https://docs.github.com/>`_ which performs no I/O of its own (a
```

2020-11-25 00:12 UTC, brettcannon commented on README.rst
> +An asynchronous `GitHub API <https://docs.github.com/en>`_ library.
```suggestion
An asynchronous `GitHub API <https://docs.github.com/>`_ library.
```

2020-11-25 00:13 UTC, brettcannon approved these changes

2020-11-25 00:25 UTC, Mariatta approved these changes
Thanks!

2020-11-25 00:26 UTC, merged