Potential Code Re-Factor and Bug Fixes
brettcannon/gidgethub pull request #140
Opened 2020-12-14 10:00 UTC by HarshCasper

## Summary

This pull request removes the Dangerous Default Argument and the assert statements from the Non-test Files. It also allowed Dictionary iteration directly. 

## Changes

This Pull Request has these Commits: 

- Remove assert statement from non-test files
- Fix dangerous default argument
- Iterate dictionary directly

## Importance

I ran a DeepSource Analysis on my fork of this repository. You can see all the issues raised by DeepSource [here](https://deepsource.io/gh/HarshCasper/gidgethub/).

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

If you do not want to use DeepSource to continuously analyze this repo, I'll remove the `.deepsource.toml` from this PR and you can merge the rest of the fixes. If you want to setup DeepSource for Continuous Analysis, I can help you set that up.

2020-12-14 17:21 UTC, Mariatta requested changes
I'm not sure about adopting DeepSource.

The fixes here broke tests and dropped code coverage, so it doesn't seem like it's improving anything, just extra maintenance burden.

At the moment I'm inclined not to accept the change.

2020-12-14 17:21 UTC, Mariatta commented on gidgethub/__init__.py
> +        if 399 >= status_code:
This is a change in behavior, not a refactoring.

2020-12-14 17:21 UTC, Mariatta commented on tests/test_sansio.py
> +        for key in headers:
This also appears to be a change in behavior.

2020-12-14 19:41 UTC, brettcannon commented
I agree with @Mariatta that I am not seeing improvements from this. And those default values are on purpose to simplify the code; they are not dangerous as none of them are actually returned to allow someone to mutate their value.

2020-12-14 19:41 UTC, closed without merging

2020-12-14 19:41 UTC, brettcannon commented
@HarshCasper thanks for at least trying!

2021-02-08 14:37 UTC, srijan-deepsource commented
Hey @brettcannon and @Mariatta! 
I just came across this PR and noticed that DeepSource generated a wrong fix. This particular bug was taken care of in our past releases.

I apologize for wasting your time on this.